#pragma once

#define MAX_DIRECTIONAL_LIGHT_NUM		8
#define MAX_SPOT_LIGHT_NUM				32
#define MAX_POINTL_LIGHT_NUM			32
#define MAX_DFFERED_POINTL_LIGHT_NUM	256

#define TEXTURE_SHADOW_WIDTH				8192
#define TEXTURE_SHADOW_HEIGHT				6144

#define TEXTURE_DIRECTIONAL_LIGHT_WIDTH		1024
#define TEXTURE_SPOT_LIGHT_WIDTH			512
#define TEXTURE_POINT_LIGHT_WIDTH			128
#define TEXTURE_POINT_CUBE_NUM				6

#define TEXTURE_DIRECTIONAL_LIGHT_HEIGHT_START	0
#define TEXTURE_SPOT_LIGHT_HEIGHT_START		2048
#define TEXTURE_POINT_LIGHT_HEIGHT_START		4096
